apiVersion: v1
kind: Namespace
metadata:
  name: blogify
  labels:
    app.kubernetes.io/part-of: blogify
    # Enforce Restricted Pod Security Standard
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
