apiVersion: v1
kind: Secret
metadata:
  name: blogify-db-secret
  namespace: blogify
  labels:
    app.kubernetes.io/part-of: blogify
type: Opaque
data:
  POSTGRES_USER: YmxvZ2lmeV91c2Vy
  POSTGRES_PASSWORD: YmxvZ2lmeV9wYXNzXzIwMjY=
  POSTGRES_DB: YmxvZ2lmeV9kYg==

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blogify-ebs-sc
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blogify-db-pvc
  namespace: blogify
  labels:
    app.kubernetes.io/part-of: blogify
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: blogify-ebs-sc
  resources:
    requests:
      storage: 10Gi
